In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)

In [3]:
df=pd.read_csv("data\Churn_Modelling.csv")

In [4]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df.shape

(10000, 14)

In [6]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

there is no null value in any data

In [7]:
# checking for duplicate values in the data 
df.duplicated().sum()

np.int64(0)

NO DUPLICATED VALUES IN THE DATA

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

checking if any customer id is been reped for not

In [16]:
df['CustomerId'].value_counts(sort='desencding')

CustomerId
15656710    1
15768163    1
15672754    1
15719276    1
15692664    1
15703563    1
15579969    1
15656062    1
15666295    1
15695474    1
15806455    1
15747927    1
15721377    1
15587133    1
15806360    1
15733491    1
15706552    1
15589475    1
15656300    1
15728693    1
15700772    1
15736816    1
15738191    1
15625047    1
15725737    1
15699309    1
15597945    1
15577657    1
15568982    1
15661507    1
15788218    1
15737452    1
15771573    1
15602280    1
15754849    1
15684171    1
15755196    1
15687946    1
15738148    1
15619360    1
15585768    1
15717426    1
15729599    1
15788448    1
15794171    1
15732963    1
15659428    1
15750181    1
15751208    1
15702014    1
15773469    1
15651280    1
15804771    1
15623944    1
15647091    1
15630053    1
15760861    1
15569590    1
15702298    1
15683553    1
15768193    1
15616550    1
15771873    1
15766205    1
15803136    1
15575185    1
15662085    1
15614049    1
15780961    1
15770811    1
15779052    1
15812518    1
15620344    1
15703793    1
15755648    1
15638424    1
15641582    1
15696061    1
15789484    1
15592461    1
15699461    1
15676966    1
15640635    1
15809248    1
15731511    1
15757535    1
15767954    1
15622897    1
15625759    1
15762418    1
15805254    1
15738751    1
15701164    1
15641732    1
15663706    1
15706021    1
15665790    1
15803526    1
15744689    1
15602312    1
15812878    1
15599195    1
15613854    1
15804919    1
15776605    1
15580146    1
15743192    1
15808582    1
15633059    1
15604348    1
15693683    1
15738721    1
15782688    1
15671137    1
15627360    1
15779659    1
15760085    1
15690673    1
15580203    1
15682472    1
15600781    1
15661670    1
15698028    1
15705512    1
15675522    1
15609618    1
15591100    1
15715951    1
15713483    1
15628145    1
15724944    1
15698932    1
15640905    1
15594408    1
15610156    1
15802381    1
15584518    1
15712543    1
15642004    1
15677871    1
15718369    1
15740404    1
15591607    1
15575492    1
15804017    1
15589975    1
15623595    1
15655007    1
15679145    1
15709368    1
15689044    1
15811589    1
15759618    1
15650237    1
15794413    1
15703264    1
15754105    1
15705707    1
15800703    1
15612350    1
15755209    1
15625524    1
15586310    1
15651022    1
15613172    1
15587562    1
15611325    1
15574692    1
15588537    1
15724623    1
15585388    1
15658929    1
15680772    1
15630910    1
15641122    1
15692132    1
15771086    1
15726931    1
15587421    1
15726676    1
15708710    1
15771977    1
15654506    1
15719377    1
15810845    1
15621075    1
15789669    1
15716334    1
15625426    1
15762615    1
15790355    1
15645248    1
15679531    1
15755262    1
15773039    1
15627801    1
15727868    1
15600974    1
15622911    1
15604482    1
15811127    1
15656176    1
15777892    1
15635905    1
15594815    1
15679200    1
15702741    1
15756850    1
15733247    1
15727829    1
15787155    1
15725311    1
15774854    1
15659366    1
15786308    1
15680920    1
15723488    1
15785542    1
15594917    1
15573152    1
15624592    1
15752047    1
15612087    1
15684181    1
15795149    1
15794056    1
15764866    1
15711540    1
15772896    1
15704769    1
15723886    1
15787174    1
15627000    1
15808473    1
15605461    1
15637753    1
15676895    1
15774393    1
15699029    1
15568748    1
15765297    1
15665834    1
15694717    1
15793726    1
15753754    1
15628112    1
15772423    1
15657566    1
15599792    1
15685500    1
15797219    1
15576269    1
15596175    1
15813844    1
15651001    1
15812009    1
15619955    1
15787071    1
15799217    1
15717398    1
15777076    1
15653857    1
15813163    1
15700696    1
15673693    1
15686776    1
15673481    1
15713853    1
15607178    1
15750803    1
15592979    1
15636684    1
15790678    1
15573112    1
15626144    1
15708608    1
15699389    1
15643024    1
15669169    1
15668893    1
15782210    1
15683562    1
15767339    1
15694456    1
15758685    1
15800116    1
15725166    1
15796505    1
15624188    1
15695699    1
15682541    1
15803976    1
15811490    1
15650068    1
15684173    1
15774510    1
15723654    1
15785819    1
15590241    1
15655774    1
15607098    1
15652266    1
15697307    1
15727556    1
15626114    1
15677512    1
15666252    1
15662736    1
15581539    1
15631868    1
15797960    1
15674398    1
15702919    1
15712287    1
15746726    1
15773972    1
15660211    1
15594898    1
15636673    1
15812191    1
15697441    1
15742668    1
15728669    1
15702669    1
15601274    1
15598493    1
15624528    1
15669064    1
15736008    1
15601848    1
15736601    1
15682757    1
15585215    1
15694408    1
15678910    1
15810834    1
15593365    1
15659420    1
15576256    1
15735203    1
15747358    1
15658935    1
15763859    1
15785869    1
15684484    1
15681081    1
15786170    1
15745844    1
15807923    1
15636624    1
15648064    1
15740476    1
15594720    1
15633537    1
15613085    1
15676715    1
15745088    1
15706365    1
15696674    1
15803716    1
15592386    1
15633950    1
15661629    1
15611759    1
15739438    1
15625461    1
15812007    1
15777352    1
15622993    1
15568240    1
15591509    1
15713578    1
15629677    1
15677371    1
15667871    1
15583456    1
15758449    1
15759537    1
15688074    1
15694506    1
15774696    1
15611579    1
15583303    1
15684042    1
15646372    1
15762218    1
15612187    1
15584766    1
15807432    1
15620505    1
15684548    1
15573456    1
15785611    1
15685226    1
15717225    1
15748936    1
15776433    1
15721181    1
15720910    1
15689294    1
15809616    1
15810432    1
15801559    1
15686302    1
15760431    1
15566594    1
15691625    1
15701376    1
15745354    1
15578045    1
15692761    1
15642291    1
15732674    1
15781589    1
15747795    1
15690452    1
15743040    1
15597602    1
15806467    1
15576313    1
15806964    1
15652883    1
15784597    1
15566111    1
15622834    1
15674551    1
15716186    1
15810418    1
15615624    1
15659843    1
15695632    1
15720559    1
15644572    1
15730460    1
15803406    1
15787470    1
15732628    1
15672145    1
15611088    1
15782735    1
15690134    1
15783501    1
15624623    1
15693737    1
15581197    1
15799384    1
15595039    1
15705521    1
15773792    1
15670039    1
15718443    1
15732778    1
15662976    1
15707362    1
15634632    1
15747960    1
15733797    1
15726631    1
15668444    1
15710825    1
15785798    1
15794396    1
15658169    1
15694860    1
15797736    1
15677538    1
15809722    1
15798888    1
15591986    1
15603156    1
15681705    1
15635367    1
15683625    1
15759298    1
15749167    1
15633283    1
15593782    1
15663252    1
15726032    1
15613786    1
15804256    1
15585865    1
15725679    1
15624170    1
15699005    1
15714689    1
15807709    1
15731744    1
15613772    1
15758639    1
15637954    1
15676519    1
15578186    1
15750658    1
15744398    1
15695585    1
15761043    1
15568506    1
15598883    1
15773890    1
15677307    1
15805565    1
15576623    1
15715527    1
15730059    1
15714485    1
15715941    1
15727688    1
15677020    1
15591995    1
15733616    1
15662403    1
15573318    1
15600258    1
15786063    1
15763274    1
15742358    1
15595766    1
15653547    1
15671256    1
15745417    1
15775912    1
15781307    1
15752081    1
15746902    1
15682048    1
15593601    1
15782236    1
15705953    1
15776223    1
15626578    1
15667896    1
15762729    1
15794142    1
15739803    1
15592846    1
15776780    1
15567832    1
15592300    1
15663478    1
15749851    1
15736112    1
15694272    1
15653849    1
15571816    1
15717046    1
15634844    1
15705515    1
15775318    1
15711309    1
15709324    1
15763063    1
15657284    1
15750141    1
15600651    1
15595440    1
15720187    1
15708916    1
15615457    1
15802593    1
15653620    1
15644753    1
15607312    1
15622003    1
15730076    1
15728505    1
15706647    1
15795564    1
15689614    1
15651674    1
15811773    1
15788126    1
15665956    1
15665678    1
15800440    1
15670080    1
15604044    1
15788291    1
15591047    1
15614782    1
15680998    1
15722010    1
15718057    1
15803689    1
15753719    1
15576352    1
15737741    1
15692671    1
15658032    1
15734674    1
15633922    1
15761986    1
15629117    1
15661249    1
15814035    1
15609286    1
15592387    1
15782569    1
15645569    1
15683503    1
15714939    1
15637476    1
15567446    1
15697183    1
15680970    1
15603925    1
15775153    1
15679587    1
15773456    1
15636444    1
15603134    1
15682585    1
15646161    1
15594594    1
15766575    1
15719352    1
15745295    1
15660271    1
15805062    1
15619857    1
15603203    1
15686611    1
15586585    1
15607170    1
15798398    1
15588350    1
15583725    1
15603323    1
15633648    1
15738181    1
15724282    1
15718673    1
15811762    1
15712403    1
15692463    1
15589030    1
15605447    1
15626900    1
15604119    1
15745307    1
15692926    1
15751710    1
15664610    1
15711889    1
15813850    1
15730447    1
15703119    1
15633064    1
15805112    1
15730830    1
15569807    1
15698786    1
15640078    1
15809663    1
15580684    1
15784844    1
15674991    1
15576368    1
15662397    1
15640825    1
15575024    1
15725511    1
15645772    1
15763218    1
15788659    1
15667215    1
15699637    1
15592937    1
15603065    1
15568595    1
15698474    1
15813741    1
15579334    1
15801277    1
15600337    1
15747867    1
15786905    1
15775238    1
15613880    1
15780804    1
15668886    1
15810978    1
15715142    1
15607040    1
15754605    1
15642394    1
15745621    1
15721024    1
15566292    1
15603436    1
15659098    1
15803457    1
15736534    1
15669516    1
15620204    1
15727299    1
15748625    1
15681068    1
15740900    1
15665238    1
15688251    1
15589493    1
15720649    1
15802741    1
15653780    1
15696859    1
15804072    1
15677369    1
15578977    1
15807609    1
15716164    1
15629448    1
15650288    1
15722548    1
15734886    1
15649423    1
15773809    1
15776231    1
15580148    1
15808621    1
15784209    1
15612966    1
15744607    1
15723873    1
15790757    1
15812750    1
15612525    1
15654238    1
15767432    1
15673570    1
15672692    1
15626742    1
15571973    1
15736879    1
15578761    1
15721658    1
15634245    1
15790314    1
15698839    1
15813034    1
15587535    1
15787619    1
15640059    1
15670755    1
15641675    1
15696231    1
15716835    1
15637414    1
15705639    1
15661036    1
15766741    1
15794278    1
15677921    1
15810864    1
15812351    1
15672056    1
15622750    1
15637876    1
15582741    1
15583212    1
15625944    1
15647099    1
15815364    1
15637979    1
15660101    1
15685997    1
15661526    1
15677305    1
15745196    1
15654060    1
15585595    1
15737051    1
15769974    1
15797227    1
15628936    1
15712551    1
15752137    1
15789158    1
15685320    1
15639314    1
15640442    1
15584091    1
15685329    1
15724296    1
15567367    1
15570134    1
15766908    1
15668747    1
15686870    1
15776807    1
15769504    1
15707473    1
15643696    1
15763431    1
15653253    1
15600739    1
15694366    1
15605284    1
15660155    1
15571221    1
15619708    1
15641655    1
15775306    1
15578980    1
15649992    1
15699430    1
15778463    1
15708917    1
15798906    1
15613319    1
15756026    1
15640280    1
15712825    1
15681554    1
15762238    1
15747542    1
15726234    1
15695846    1
15639788    1
15596914    1
15666633    1
15660535    1
15660602    1
15603830    1
15757811    1
15765311    1
15716155    1
15596939    1
15747807    1
15591969    1
15806438    1
15734565    1
15586959    1
15608968    1
15592222    1
15806983    1
15672012    1
15599433    1
15737792    1
15707567    1
15727915    1
15585888    1
15589488    1
15585036    1
15575883    1
15780628    1
15625881    1
15797964    1
15614215    1
15794916    1
15809100    1
15807663    1
15809087    1
15686137    1
15760550    1
15693864    1
15686436    1
15601589    1
15745012    1
15677610    1
15794048    1
15572265    1
15725811    1
15646558    1
15697497    1
15656333    1
15800228    1
15581229    1
15653762    1
15674840    1
15803764    1
15794549    1
15692750    1
15799422    1
15710424    1
15646810    1
15756804    1
15808017    1
15686983    1
15805449    1
15697000    1
15669987    1
15772781    1
15585255    1
15780140    1
15768104    1
15600462    1
15702968    1
15625021    1
15591711    1
15721935    1
15777211    1
15743007    1
15785519    1
15571928    1
15585362    1
15746490    1
15599660    1
15693814    1
15754713    1
15724848    1
15814275    1
15675964    1
15794580    1
15786014    1
15792388    1
15709737    1
15642041    1
15632210    1
15654700    1
15782390    1
15733119    1
15633461    1
15628303    1
15636731    1
15658485    1
15601026    1
15753337    1
15743411    1
15797748    1
15733114    1
15593773    1
15719856    1
15792328    1
15775625    1
15710404    1
15655961    1
15566091    1
15781465    1
15804586    1
15676521    1
15754084    1
15599289    1
15668032    1
15662100    1
15613630    1
15675316    1
15790299    1
15737795    1
15634141    1
15700476    1
15790782    1
15590876    1
15677135    1
15628034    1
15619529    1
15731522    1
15631681    1
15571002    1
15660429    1
15671139    1
15606149    1
15785899    1
15630328    1
15620981    1
15783659    1
15741336    1
15745324    1
15709295    1
15729362    1
15685357    1
15705620    1
15779711    1
15605918    1
15801488    1
15805955    1
15605926    1
15641009    1
15720893    1
15589805    1
15602084    1
15580956    1
15731815    1
15753831    1
15582797    1
15686164    1
15806926    1
15745527    1
15681206    1
15664521    1
15613749    1
15655339    1
15756475    1
15704770    1
15807008    1
15792360    1
15566156    1
15624729    1
15642937    1
15799515    1
15582616    1
15570060    1
15573086    1
15739189    1
15701602    1
15723685    1
15701301    1
15633897    1
15592089    1
15691111    1
15787772    1
15659557    1
15608114    1
15645621    1
15810218    1
15623521    1
15782899    1
15724563    1
15682639    1
15765014    1
15717164    1
15654673    1
15600583    1
15602010    1
15587451    1
15770424    1
15686936    1
15585961    1
15603594    1
15655274    1
15698442    1
15799811    1
15750765    1
15569050    1
15577478    1
15581479    1
15631054    1
15668958    1
15652955    1
15689176    1
15695475    1
15750243    1
15667521    1
15681174    1
15688071    1
15686345    1
15769948    1
15767864    1
15759805    1
15729279    1
15769499    1
15743016    1
15798348    1
15623471    1
15715003    1
15623828    1
15705860    1
15645103    1
15793949    1
15644200    1
15785980    1
15779059    1
15570417    1
15593969    1
15692317    1
15780870    1
15586970    1
15648075    1
15628674    1
15680303    1
15599131    1
15688963    1
15692744    1
15699598    1
15762198    1
15631189    1
15692991    1
15650933    1
15812197    1
15706186    1
15706534    1
15798521    1
15696098    1
15708063    1
15646513    1
15591257    1
15692583    1
15663438    1
15699911    1
15589195    1
15748856    1
15633650    1
15729832    1
15750929    1
15762937    1
15682618    1
15790497    1
15625698    1
15780144    1
15746410    1
15782219    1
15768201    1
15673055    1
15724127    1
15604295    1
15813168    1
15689081    1
15621687    1
15624347    1
15585198    1
15784092    1
15604304    1
15649744    1
15645517    1
15585241    1
15759381    1
15592583    1
15723250    1
15626608    1
15626147    1
15648800    1
15714750    1
15798424    1
15592229    1
15616330    1
15678886    1
15660316    1
15618182    1
15624293    1
15590476    1
15656121    1
15732660    1
15706899    1
15762110    1
15733974    1
15628205    1
15685309    1
15750258    1
15647301    1
15593973    1
15645316    1
15627305    1
15596800    1
15789955    1
15672704    1
15589358    1
15752463    1
15722993    1
15773906    1
15616529    1
15671209    1
15575581    1
15601688    1
15694821    1
15605965    1
15763625    1
15716134    1
15566251    1
15569247    1
15698510    1
15645269    1
15614220    1
15702430    1
15633419    1
15723907    1
15750776    1
15600997    1
15752731    1
15781802    1
15719348    1
15690664    1
15690007    1
15811327    1
15741295    1
15768006    1
15766887    1
15669899    1
15589754    1
15600992    1
15755638    1
15624428    1
15570326    1
15814032    1
15782454    1
15651369    1
15604217    1
15721292    1
15588670    1
15808182    1
15697789    1
15640454    1
15590820    1
15650351    1
15710456    1
15769169    1
15678058    1
15813444    1
15739131    1
15578866    1
15573769    1
15779947    1
15589572    1
15686909    1
15636935    1
15791279    1
15639882    1
15719302    1
15589257    1
15795228    1
15755649    1
15625080    1
15674148    1
15624229    1
15813590    1
15738174    1
15658969    1
15715667    1
15616451    1
15594864    1
15599268    1
15724307    1
15650098    1
15569451    1
15724334    1
15651052    1
15804602    1
15749482    1
15742480    1
15607598    1
15578515    1
15613844    1
15775572    1
15733387    1
15628298    1
15654229    1
15616280    1
15697625    1
15654654    1
15812272    1
15730038    1
15696900    1
15682528    1
15711288    1
15721189    1
15658052    1
15616709    1
15593331    1
15813132    1
15760774    1
15617934    1
15660422    1
15619626    1
15634267    1
15774155    1
15600700    1
15684865    1
15575410    1
15607537    1
15726557    1
15747591    1
15794870    1
15743532    1
15701265    1
15740494    1
15647402    1
15781989    1
15615032    1
15610383    1
15699523    1
15658306    1
15814930    1
15702789    1
15803681    1
15770030    1
15634896    1
15641690    1
15721719    1
15690182    1
15683195    1
15625916    1
15612064    1
15756539    1
15793854    1
15671322    1
15723339    1
15617078    1
15781586    1
15749050    1
15662291    1
15732199    1
15737748    1
15584363    1
15687752    1
15636589    1
15679611    1
15813917    1
15688880    1
15597239    1
15565701    1
15590993    1
15658532    1
15742229    1
15609510    1
15778287    1
15779182    1
15671590    1
15750497    1
15759317    1
15690079    1
15662294    1
15638806    1
15709117    1
15800434    1
15749004    1
15683930    1
15671097    1
15800856    1
15724620    1
15795166    1
15572360    1
15793247    1
15803365    1
15688007    1
15682773    1
15729975    1
15765537    1
15629244    1
15598846    1
15704483    1
15596493    1
15763612    1
15665077    1
15720702    1
15808689    1
15734634    1
15644833    1
15576602    1
15596181    1
15645778    1
15640268    1
15609824    1
15645511    1
15761132    1
15612108    1
15650889    1
15682563    1
15576683    1
15664772    1
15734942    1
15796721    1
15575417    1
15742854    1
15645572    1
15574331    1
15704954    1
15722364    1
15746326    1
15769005    1
15615029    1
15683403    1
15623644    1
15596552    1
15635435    1
15613141    1
15778135    1
15576162    1
15668445    1
15777826    1
15714567    1
15691104    1
15574004    1
15774738    1
15771942    1
15723006    1
15792722    1
15791767    1
15722902    1
15745843    1
15627232    1
15621353    1
15689514    1
15719958    1
15789095    1
15683841    1
15754068    1
15694409    1
15787835    1
15727281    1
15684196    1
15775295    1
15674526    1
15704586    1
15672756    1
15690647    1
15696637    1
15617982    1
15714466    1
15743067    1
15571752    1
15682834    1
15808228    1
15587233    1
15600821    1
15629617    1
15612494    1
15797276    1
15721487    1
15613282    1
15619029    1
15670481    1
15775546    1
15628947    1
15754796    1
15748797    1
15697095    1
15582180    1
15646276    1
15730540    1
15589221    1
15794874    1
15742378    1
15753969    1
15705657    1
15649280    1
15774166    1
15667651    1
15685150    1
15620507    1
15797733    1
15588986    1
15693904    1
15710164    1
15814268    1
15579062    1
15806967    1
15574068    1
15742632    1

there is no elemnet with same customer id

In [17]:
df.sample(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3602,3603,15582762,Mazzanti,667,Spain,Male,77,2,0.00,1,1,1,34702.92,0
921,922,15743411,Chiawuotu,609,Spain,Male,61,1,0.00,1,1,0,22447.85,1
859,860,15809087,Landry,598,France,Male,64,1,0.00,2,1,0,195635.30,1
9385,9386,15759244,Boone,687,Germany,Male,44,8,95368.14,2,1,1,1787.85,0
3805,3806,15597394,Rhodes,668,Spain,Male,34,0,0.00,1,0,0,99984.86,0

In [19]:
df['Surname'].value_counts()

Surname
Smith                      32
Scott                      29
Martin                     29
Walker                     28
Brown                      26
Genovese                   25
Yeh                        25
Shih                       25
Wright                     24
Maclean                    24
Ma                         23
Wilson                     23
Fanucci                    23
White                      23
Lu                         22
Wang                       22
Moore                      22
Chu                        22
Johnson                    22
Mai                        21
Sun                        21
Thompson                   21
McGregor                   21
Hughes                     20
Palerma                    20
Kennedy                    20
Kerr                       20
Jamieson                   20
Lo                         20
Graham                     20
Trevisani                  20
Fang                       20
Kao                        20
Mitchell                   20
Young                      20
Shen                       20
Watson                     20
Miller                     20
Cameron                    19
Wallace                    19
Bergamaschi                19
Crawford                   19
Ts'ui                      19
Wei                        19
Gordon                     19
Tuan                       19
Pan                        19
H?                         19
Ko                         19
Pai                        19
McDonald                   19
McKay                      19
Lung                       19
Anderson                   19
Duncan                     19
Sung                       18
Tu                         18
Tien                       18
Lin                        18
King                       18
Ross                       18
Burns                      18
T'ien                      18
Fleming                    18
He                         18
Mao                        18
Hsia                       18
Hill                       17
Manna                      17
Grant                      17
McIntyre                   17
Johnston                   17
Wan                        17
Boyle                      17
Davidson                   17
Hsing                      17
Feng                       17
Shaw                       17
Tang                       17
P'eng                      17
Chung                      17
Endrizzi                   17
Gibson                     17
Chiu                       17
Cocci                      17
Ch'ang                     17
Tsao                       17
Findlay                    17
Greco                      17
Manfrin                    17
Su                         16
Forbes                     16
Henderson                  16
Clark                      16
McKenzie                   16
Chin                       16
Robertson                  16
Johnstone                  16
Stevenson                  16
Trevisano                  16
Ch'iu                      16
Ferri                      16
Wu                         16
Yao                        16
Pisano                     16
Ku                         16
Kung                       16
Hsieh                      16
Fu                         16
Calabresi                  16
Teng                       15
Hs?                        15
Sinclair                   15
Taylor                     15
Mazzanti                   15
Douglas                    15
Black                      15
Hung                       15
Murray                     15
Hamilton                   15
Hsiung                     15
Thomson                    15
Wood                       15
Ts'ai                      15
Cattaneo                   15
Allan                      15
Marshall                   15
Lombardo                   15
Yen                        14
Buccho                     14
Fraser                     14
Meng                       14
Tan                        14
Chang                      14
Kang                       14
Williamson                 14
Liang                      14
Chia                       14
Pinto                      14
Fan                        14
Fiorentini                 14
Sutherland                 14
Chiang                     14
Boni                       14
Sal                        14
Capon                      14
Pirozzi                    14
L?                         14
Simmons                    14
Hsueh                      14
McMillan                   14
Rossi                      14
Chuang                     14
Ch'eng                     13
Esposito                   13
Pisani                     13
Milne                      13
Ch'in                      13
She                        13
Y?an                       13
Niu                        13
Gray                       13
Lai                        13
Yuan                       13
T'ang                      13
Fiorentino                 13
Hunter                     13
Cheng                      13
MacDonald                  13
Piccio                     13
Moss                       13
Calabrese                  13
Dellucci                   13
Yang                       13
Napolitani                 13
Campbell                   13
T'ao                       13
Mazzi                      13
Toscani                    13
Lo Duca                    13
Alexander                  13
Millar                     13
Tsui                       13
Ch'ien                     13
Y?                         13
Macleod                    13
Ts'ao                      12
Stewart                    12
Tai                        12
Liao                       12
Jen                        12
Liu                        12
Chao                       12
Beneventi                  12
Shao                       12
Chiemenam                  12
Simpson                    12
Bruno                      12
Morrison                   12
Lettiere                   12
Kelly                      12
Bellucci                   12
Russell                    12
Trentino                   12
Lei                        12
Genovesi                   12
Williams                   12
Hao                        12
Arcuri                     12
Chien                      12
Padovesi                   12
K'ung                      12
Milanesi                   12
Castiglione                12
Lucchesi                   12
Cremonesi                  12
Lorenzo                    12
Palermo                    12
Muir                       12
Ting                       12
Hu                         12
Huang                      12
Li                         12
Donaldson                  12
Robinson                   12
Loggia                     12
Fallaci                    11
Lombardi                   11
Craig                      11
Chukwuemeka                11
Ferguson                   11
Angelo                     11
Davide                     11
Murphy                     11
Ritchie                    11
Lucciano                   11
Li Fonti                   11
Padovano                   11
Milani                     11
Tao                        11
Yin                        11
Marino                     11
Folliero                   11
Longo                      11
Paterson                   11
Udinese                    11
Bell                       11
Pagnotto                   11
Hsu                        11
Zetticci                   11
Mancini                    11
Christie                   11
Han                        11
Lori                       11
Toscano                    11
K?                         11
Munro                      11
Ho                         11
Davis                      11
Gallo                      11
Giordano                   11
Lucchese                   10
Sabbatini                  10
Ni                         10
Romani                     10
McIntosh                   10
Bianchi                    10
Chou                       10
Evans                      10
Marcelo                    10
Jones                      10
Carpenter                  10
Tung                       10
Ch'en                      10
Cunningham                 10
Bailey                     10
Yu                         10
Woods                      10
De Luca                    10
Adams                      10
Olisaemeka                 10
Hou                        10
Kuo                        10
Watt                       10
Tsou                       10
Nwankwo                     9
Clements                    9
Ferrari                     9
Stephenson                  9
Jackson                     9
Mackenzie                   9
Power                       9
Udinesi                     9
Moretti                     9
Iadanza                     9
Tseng                       9
Cox                         9
Conti                       9
Ricci                       9
Wall                        9
Sagese                      9
Marchesi                    9
Azubuike                    9
Doherty                     9
Napolitano                  9
Greece                      9
Ginikanwa                   8
Brookes                     8
Barese                      8
Aitken                      8
Hsiao                       8
Palmer                      8
Hay                         8
Freeman                     8
Cartwright                  8
Akabueze                    8
Lucas                       8
Howells                     8
Vincent                     8
Nucci                       8
Nicholls                    8
Chukwudi                    8
Reid                        8
Page                        8
Onyemauchechukwu            8
Rowe                        8
Ball                        8
Costa                       8
Ifeatu                      8
P'an                        8
DeRose                      8
Chambers                    8
Romano                      8
Docherty                    8
Hunt                        8
Thomas                      8
Chen                        8
Hudson                      8
Milano                      8
Green                       8
Bradley                     8
Walton                      8
Knight                      8
Benson                      8
Monaldo                     8
Saunders                    8
Rizzo                       8
Colombo                     8
Onio                        8
McLean                      7
Hancock                     7
Mills                       7
Rowley                      7
Eluemuno                    7
Chinedum                    7
Aksenov                     7
Hs?eh                       7
Oluchukwu                   7
Baresi                      7
Buckley                     7
Carter                      7
Fuller                      7
Lane                        7
Volkova                     7
Sanders                     7
Chinomso                    7
Akobundu                    7
Nwabugwu                    7
Yobanna                     7
Iloerika                    7
Lawrence                    7
Russo                       7
Parry                       7
Nnachetam                   7
Coates                      7
Mackay                      7
Dickson                     7
Okechukwu                   7
Bryant                      7
Atkins                      7
Peng                        7
Kodilinyechukwu             7
Franklin                    7
Piazza                      7
Bruce                       7
Webb                        7
Barry                       7
Hanson                      7
Reilly                      7
Tsai                        7
Onwumelu                    7
Nnonso                      7
Nebechukwu                  7
Moran                       7
Panicucci                   7
Trentini                    7
Hawkins                     7
Obiajulu                    7
Chan                        7
Rose                        7
Obialo                      7
Burke                       7
Kent                        7
Parkes                      7
Nnaife                      7
Chiazagomekpere             7
Roberts                     7
Davison                     7
Hargreaves                  7
Chidubem                    7
Long                        7
Onyemere                    7
Dale                        7
Enyinnaya                   6
Hardy                       6
Parsons                     6
Thorpe                      6
Woronoff                    6
Chiganu                     6
Iweobiegbunam               6
Zito                        6
Amaechi                     6
Osborne                     6
Norman                      6
Ford                        6
Wade                        6
Zikoranachidimma            6
Giles                       6
Townsend                    6
Siciliano                   6
Uspensky                    6
Okeke                       6
Okwudilichukwu              6
Baker                       6
Nixon                       6
Ijendu                      6
Iroawuchi                   6
Briggs                      6
Vasilyeva                   6
Ugochukwu                   6
Stanley                     6
Ellis                       6
Hyde                        6
Siciliani                   6
Alexeeva                    6
Owens                       6
Otutodilinna                6
Blackburn                   6
Anayolisa                   6
Madukwe                     6
Olisanugo                   6
Bevan                       6
Chinwendu                   6
Obiuto                      6
Coles                       6
Osonduagwuike               6
Onyekaozulu                 6
Stevens                     6
Barnes                      6
Matthews                    6
Okonkwo                     6
Brennan                     6
Balashov                    6
Chienezie                   6
Goddard                     6
Wong                        6
Allen                       6
Doyle                       6
Steele                      6
Cross                       6
West                        6
Gregory                     6
Bates                       6
Todd                        6
Mason                       6
Gibbons                     6
Onwuamaeze                  6
Storey                      6
Goliwe                      6
Warner                      6
Browne                      6
Tomlinson                   6
Booth                       6
Trevisan                    6
Pickering                   6
Nebechi                     6
Berry                       6
Glover                      6
Atkinson                    6
Somadina                    6
Andrews                     6
Chibueze                    6
Myers                       6
Holloway                    6
Nwebube                     6
Chibugo                     5
Golubev                     5
Ndubueze                    5
Udegbulam                   5
Bray                        5
Fomin                       5
Brooks                      5
Chidimma                    5
Chapman                     5
Burgess                     5
Uspenskaya                  5
Lord                        5
Azuka                       5
Dawson                      5
Leonard                     5
Chiemela                    5
Pugliesi                    5
Gorbunov                    5
Howe                        5
Warren                      5
Owen                        5
Abramovich                  5
Cook                        5
Turnbull                    5
Patterson                   5
Mellor                      5
Hale                        5
Lewis                       5
Summers                     5
Chiedozie                   5
Davies                      5
Onyemachukwu                5
Conway                      5
Nwachukwu                   5
O'Donnell                   5
Sullivan                    5
Yobachi                     5
Gilbert                     5
Nicholson                   5
Otutodilichukwu             5
Porter                      5
Watkins                     5
Kambinachi                  5
Tretiakova                  5
Jideofor                    5
Powell                      5
Osinachi                    5
Chidozie                    5
Welch                       5
Butler                      5
Chigozie                    5
Harris                      5
Chukwufumnanya              5
Ngozichukwuka               5
Yobachukwu                  5
Pope                        5
Francis                     5
Akhtar                      5
North                       5
Butusov                     5
Heath                       5
Norris                      5
Nnanna                      5
Reed                        5
John                        5
Gould                       5
Parkin                      5
Sims                        5
Griffin                     5
Nnamutaezinwa               5
Chiawuotu                   5
Lamb                        5
Chiekwugo                   5
Norton                      5
Okwudiliolisa               5
Ward                        5
Matveyeva                   5
Savage                      5
Ozerova                     5
Hall                        5
Chukwukadibia               5
Ogbonnaya                   5
Marsden                     5
Arnold                      5
Onyekachi                   5
Hayward                     5
Ojiofor                     5
Chukwualuka                 5
Okwuadigbo                  5
Robson                      5
Oliver                      5
Gardiner                    5
Alexeyeva                   5
T'an                        5
Byrne                       5
Nkemakolam                  5
Dunn                        5
Onuchukwu                   5
Lloyd                       5
Ikenna                      5
Fowler                      5
Collins                     5
Humphries                   5
Archer                      5
Anenechukwu                 5
Ibezimako                   5
Dyer                        5
Phillips                    5
Watts                       5
Lazarev                     5
Price                       5
Chizuoke                    5
Nnamdi                      5
Ajuluchukwu                 5
Caldwell                    5
Carr                        5
Collier                     5
Law                         5
Bentley                     5
Obidimkpa                   5
Onyeorulu                   5
Azikiwe                     5
Perry                       5
Holden                      5
Nkemjika                    5
Kay                         5
Abbott                      4
Clarke                      4
Konovalova                  4
Davey                       4
Morley                      4
Ingram                      4
Gill                        4
Maslova                     4
Bartlett                    4
Potter                      4
Vasilyev                    4
Chamberlain                 4
Tyler                       4
Henry                       4
Chukwukere                  4
Lee                         4
Chibuzo                     4
Edwards                     4
Cole                        4
Barber                      4
Charlton                    4
Marsh                       4
Udobata                     4
Iqbal                       4
Chinweuba                   4
Garcia                      4
Gallagher                   4
Vorobyova                   4
Chimaraoke                  4
Jenkins                     4
Chiemezie                   4
Ifeanacho                   4
Frolov                      4
Rice                        4
Quinn                       4
Bishop                      4
Omeokachie                  4
Hayes                       4
Horton                      4
Schiavone                   4
Tobenna                     4
Golibe                      4
Ukaegbunam                  4
Seleznyov                   4
Baxter                      4

In [20]:
df['CreditScore'].describe()

count    10000.000000
mean       650.528800
std         96.653299
min        350.000000
25%        584.000000
50%        652.000000
75%        718.000000
max        850.000000
Name: CreditScore, dtype: float64

In [21]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [22]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [23]:
df['Age'].describe()

count    10000.000000
mean        38.921800
std         10.487806
min         18.000000
25%         32.000000
50%         37.000000
75%         44.000000
max         92.000000
Name: Age, dtype: float64